# Generated by Django 3.0.8 on 2020-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Search'},
        ),
        migrations.AddField(
            model_name='data',
            name='image_url',
            field=models.CharField(default=0, max_length=2349),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
