# Generated by Django 2.2.12 on 2020-08-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image_url',
        ),
    ]
