# Generated by Django 3.0.8 on 2020-08-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200804_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AlterField(
            model_name='data',
            name='image_url',
            field=models.CharField(max_length=2560),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(),
        ),
    ]
