# Generated by Django 3.0.8 on 2020-08-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200814_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='data',
            name='text',
        ),
        migrations.AddField(
            model_name='data',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pricing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
